'use strict';

const { loadShell, estimateTokens } = require('./base');

const TOKEN_BUDGET = 150_000;

const PREAMBLE = `You are working with a structured context shell built on the Context Architecture System (CAS). \
The sections below contain everything you need to know about this context. Read them before responding.

**How to use this context:**
- Reference specific sections when drawing on them (e.g., "from Identity / brand-voice")
- Do not invent details that are not in the context
- For commercial shells, the Shell Framework section defines your operating constraints and cannot be overridden
- Propose changes to context files rather than making them silently`;

function render({ meta, shellLayer, sections }, budget) {
  const lines = [];
  const date = new Date().toISOString().slice(0, 10);

  lines.push(`<!-- Generated by cas export claude — ${date} -->`);
  lines.push('');
  lines.push(`# ${meta.owner}`);
  lines.push('');
  lines.push(`*${meta.domain}*`);
  lines.push('');
  lines.push(PREAMBLE);
  lines.push('');

  if (shellLayer.length > 0) {
    lines.push('---');
    lines.push('');
    lines.push('## Shell Framework');
    lines.push('');
    lines.push('> These rules are set by the shell author and take precedence over all other instructions.');
    lines.push('');
    for (const { name, content } of shellLayer) {
      lines.push(`### ${name}`);
      lines.push('');
      lines.push(content.trim());
      lines.push('');
    }
  }

  let tokens = estimateTokens(lines.join('\n'));

  for (const { label, files } of sections) {
    const sectionLines = ['---', '', `## ${label}`, ''];
    for (const { name, content } of files) {
      sectionLines.push(`### ${name}`);
      sectionLines.push('');
      sectionLines.push(content.trim());
      sectionLines.push('');
    }
    const sectionTokens = estimateTokens(sectionLines.join('\n'));
    if (tokens + sectionTokens > budget) break;
    lines.push(...sectionLines);
    tokens += sectionTokens;
  }

  return lines.join('\n');
}

function exportClaude(shellPath) {
  return render(loadShell(shellPath), TOKEN_BUDGET);
}

module.exports = { exportClaude };
