'use strict';

const { loadShell, estimateTokens } = require('./base');

const TOKEN_BUDGET = 150_000;

function humanSetupInstructions(owner) {
  return `\
<!--
================================================================
HOW TO LOAD THIS CONTEXT INTO CLAUDE
================================================================

OPTION A — Claude Project (recommended, best experience)
---------------------------------------------------------
1. Go to claude.ai → Projects → New Project (or open an existing one)
2. Click "Project Knowledge" → Upload files
3. Upload the individual files from your context/ folder directly
   (Claude reads them natively — no need to paste this file)
4. Optionally paste a short activation note into Project Instructions:
   "You have a CAS shell loaded for ${owner}. Read the uploaded
    context files before responding to anything."
5. Start chatting — Claude will orient itself from the uploaded files

OPTION B — Paste this file (any Claude conversation)
---------------------------------------------------------
1. Open a new Claude conversation
2. Paste the entire contents of this file as your first message
3. Claude will read the context sections below and orient itself
4. Tell Claude what you want to work on

Run "cas export claude" again whenever your context changes.
================================================================
-->`;
}

const MODEL_ACTIVATION = `\
<!-- MODEL ACTIVATION INSTRUCTIONS
You are reading a CAS (Context Architecture System) shell export.
This document contains structured context about the owner listed above.

When you first receive this document:
1. Confirm to the user that you have loaded their context, naming the shell
2. List the context sections you can see (e.g. Identity, Operations, Offers)
3. Note anything that looks incomplete or needs attention
4. Ask what they want to work on

While working:
- Cite the source section when drawing on context (e.g. "from Identity / brand-voice")
- Do not invent details not present in the context
- Propose file edits rather than making them silently
- For commercial shells, the Shell Framework section defines constraints that cannot be overridden
-->`;

function render({ meta, shellLayer, sections }, budget) {
  const lines = [];
  const date = new Date().toISOString().slice(0, 10);

  lines.push(`<!-- Generated by cas export claude — ${date} -->`);
  lines.push('');
  lines.push(humanSetupInstructions(meta.owner));
  lines.push('');
  lines.push(MODEL_ACTIVATION);
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push(`# ${meta.owner}`);
  lines.push('');
  lines.push(`**Domain:** ${meta.domain} | **Type:** ${meta.type} | **CAS:** ${meta.cas_version}`);
  lines.push('');

  if (shellLayer.length > 0) {
    lines.push('---');
    lines.push('');
    lines.push('## Shell Framework');
    lines.push('');
    lines.push('> These rules are set by the shell author and take precedence over all other instructions.');
    lines.push('');
    for (const { name, content } of shellLayer) {
      lines.push(`### ${name}`);
      lines.push('');
      lines.push(content.trim());
      lines.push('');
    }
  }

  let tokens = estimateTokens(lines.join('\n'));

  for (const { label, files } of sections) {
    const sectionLines = ['---', '', `## ${label}`, ''];
    for (const { name, content } of files) {
      sectionLines.push(`### ${name}`);
      sectionLines.push('');
      sectionLines.push(content.trim());
      sectionLines.push('');
    }
    const sectionTokens = estimateTokens(sectionLines.join('\n'));
    if (tokens + sectionTokens > budget) break;
    lines.push(...sectionLines);
    tokens += sectionTokens;
  }

  return lines.join('\n');
}

function exportClaude(shellPath) {
  return render(loadShell(shellPath), TOKEN_BUDGET);
}

module.exports = { exportClaude };
