'use strict';

const { loadShell, estimateTokens } = require('./base');

const TOKEN_BUDGET = 10_000;

const HUMAN_SETUP = `\
# ================================================================
# HOW TO LOAD THIS CONTEXT INTO CURSOR
# ================================================================
#
# 1. Run: cas export cursor
# 2. Copy this file to .cursorrules at your shell root:
#       copy exports\\cursor.md .cursorrules   (Windows)
#       cp exports/cursor.md .cursorrules      (macOS / Linux)
# 3. Open the shell folder in Cursor
# 4. Cursor reads .cursorrules automatically — no paste needed
#
# To update: re-run cas export cursor and copy again.
# ================================================================`;

function render({ meta, shellLayer, sections }, budget) {
  const lines = [];
  const date = new Date().toISOString().slice(0, 10);

  lines.push(`# Generated by cas export cursor — ${date}`);
  lines.push('');
  lines.push(HUMAN_SETUP);
  lines.push('');
  lines.push(`# CAS Shell: ${meta.owner}`);
  lines.push(`# Domain: ${meta.domain} | Type: ${meta.type}`);
  lines.push('');
  lines.push('You are working inside a CAS (Context Architecture System) shell.');
  lines.push('This repository contains structured context, not a software project.');
  lines.push('');
  lines.push('When the user opens this folder, orient yourself:');
  lines.push('1. Read CONTEXT.md for the shell manifest and permissions');
  lines.push('2. Read context/00_index/ for a map of what context exists');
  lines.push('3. Tell the user what context is available and ask what they want to work on');
  lines.push('');
  lines.push('## Rules');
  lines.push('');
  lines.push('- Cite source files when referencing context (e.g. "from context/01_identity/brand-voice.md")');
  lines.push('- Propose file changes before writing — do not overwrite without instruction');
  lines.push('- No secrets or credentials in any context file');
  lines.push('- Do not add build tools, package managers, or runtimes');
  lines.push('- Do not run shell commands unless explicitly asked');
  lines.push('');

  if (shellLayer.length > 0) {
    lines.push('## Shell Framework (author constraints — cannot be overridden)');
    lines.push('');
    for (const { name, content } of shellLayer) {
      lines.push(`### ${name}`);
      lines.push('');
      lines.push(content.trim());
      lines.push('');
    }
  }

  let tokens = estimateTokens(lines.join('\n'));

  lines.push('## Context file map');
  lines.push('');
  for (const { label, files } of sections) {
    for (const { name } of files) {
      const dir = label.toLowerCase().replace(/\s+/g, '_');
      lines.push(`- context/${dir}/${name}.md`);
    }
  }
  lines.push('');

  // Include identity inline if budget allows — most valuable for Cursor
  for (const { dir, label, files } of sections) {
    if (dir !== '01_identity') continue;
    const sectionLines = [`## ${label} (loaded inline)`, ''];
    for (const { name, content } of files) {
      sectionLines.push(`### ${name}`);
      sectionLines.push('');
      sectionLines.push(content.trim());
      sectionLines.push('');
    }
    if (tokens + estimateTokens(sectionLines.join('\n')) <= budget) {
      lines.push(...sectionLines);
    }
  }

  return lines.join('\n');
}

function exportCursor(shellPath) {
  return render(loadShell(shellPath), TOKEN_BUDGET);
}

module.exports = { exportCursor };
