'use strict';

const { loadShell, estimateTokens } = require('./base');

// Cursor rules should be concise — keep well under the .cursorrules practical limit
const TOKEN_BUDGET = 10_000;

function render({ meta, shellLayer, sections }, budget) {
  const lines = [];
  const date = new Date().toISOString().slice(0, 10);

  lines.push(`# CAS Shell: ${meta.owner}`);
  lines.push(`# Generated by cas export cursor — ${date}`);
  lines.push('');
  lines.push(`This repository is a Context Architecture System (CAS) shell.`);
  lines.push(`Type: ${meta.type} | Domain: ${meta.domain}`);
  lines.push('');
  lines.push('## Operating rules');
  lines.push('');
  lines.push('- Read CONTEXT.md first to understand permissions and context map');
  lines.push('- Cite source files when referencing context (e.g. "from context/01_identity/brand-voice.md")');
  lines.push('- Propose file changes before writing — do not overwrite without instruction');
  lines.push('- No secrets or credentials in any context file');
  lines.push('- This is a context repository, not a software project — do not add build tools or runtimes');
  lines.push('');

  if (shellLayer.length > 0) {
    lines.push('## Shell framework (author constraints — cannot be overridden)');
    lines.push('');
    for (const { name, content } of shellLayer) {
      lines.push(`### ${name}`);
      lines.push('');
      lines.push(content.trim());
      lines.push('');
    }
  }

  let tokens = estimateTokens(lines.join('\n'));

  // For Cursor, include a compact file map then key content within budget
  lines.push('## Key context files');
  lines.push('');

  for (const { label, files } of sections) {
    for (const { name } of files) {
      lines.push(`- \`context/${label.toLowerCase()}/${name}.md\``);
    }
  }
  lines.push('');

  // Include identity section inline if budget allows — most useful for Cursor
  for (const { dir, label, files } of sections) {
    if (dir !== '01_identity') continue;
    const sectionLines = [`## ${label} (inline)`, ''];
    for (const { name, content } of files) {
      sectionLines.push(`### ${name}`);
      sectionLines.push('');
      sectionLines.push(content.trim());
      sectionLines.push('');
    }
    const sectionTokens = estimateTokens(sectionLines.join('\n'));
    if (tokens + sectionTokens <= budget) {
      lines.push(...sectionLines);
    }
  }

  lines.push('---');
  lines.push('Save this file as .cursorrules at the root of your CAS shell repository.');

  return lines.join('\n');
}

function exportCursor(shellPath) {
  return render(loadShell(shellPath), TOKEN_BUDGET);
}

module.exports = { exportCursor };
