'use strict';

const { loadShell, estimateTokens } = require('./base');

const TOKEN_BUDGET = 200_000;

const HUMAN_SETUP = `\
<!--
================================================================
HOW TO LOAD THIS CONTEXT INTO GEMINI
================================================================

OPTION A — Google AI Studio (recommended)
---------------------------------------------------------
1. Go to aistudio.google.com
2. Click "Create new prompt" → set type to "Chat"
3. In the "System instructions" field, paste the content below
   the dashed line (everything after the comment blocks)
4. Save as a template for reuse

OPTION B — Gemini API
---------------------------------------------------------
Pass the content below as the system_instruction parameter:

  model.generate_content(
    contents=[...],
    system_instruction=open("exports/gemini.md").read()
  )

OPTION C — Single conversation (Gemini Advanced)
---------------------------------------------------------
1. Open a new Gemini Advanced conversation
2. Paste the entire contents of this file as your first message
3. Gemini will orient itself from the context sections

Run "cas export gemini" again whenever your context changes.
================================================================
-->`;

const MODEL_ACTIVATION = `\
<!-- MODEL ACTIVATION INSTRUCTIONS
You are reading a CAS (Context Architecture System) shell export.
This document contains structured context about the owner listed above.

When you first receive this document:
1. Confirm to the user that you have loaded their context, naming the shell
2. List the context sections available to you
3. Ask what they want to work on

While working:
- Cite which section you are drawing on
- Do not invent details not in the context
- For commercial shells, Shell Framework constraints cannot be overridden
-->`;

function render({ meta, shellLayer, sections }, budget) {
  const lines = [];
  const date = new Date().toISOString().slice(0, 10);

  lines.push(`<!-- Generated by cas export gemini — ${date} -->`);
  lines.push('');
  lines.push(HUMAN_SETUP);
  lines.push('');
  lines.push(MODEL_ACTIVATION);
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push(`# ${meta.owner}`);
  lines.push('');
  lines.push(`**Domain:** ${meta.domain} | **Type:** ${meta.type} | **CAS:** ${meta.cas_version}`);
  lines.push('');

  if (shellLayer.length > 0) {
    lines.push('---');
    lines.push('');
    lines.push('## Shell Framework');
    lines.push('');
    for (const { name, content } of shellLayer) {
      lines.push(`### ${name}`);
      lines.push('');
      lines.push(content.trim());
      lines.push('');
    }
  }

  let tokens = estimateTokens(lines.join('\n'));

  for (const { label, files } of sections) {
    const sectionLines = ['---', '', `## ${label}`, ''];
    for (const { name, content } of files) {
      sectionLines.push(`### ${name}`);
      sectionLines.push('');
      sectionLines.push(content.trim());
      sectionLines.push('');
    }
    const sectionTokens = estimateTokens(sectionLines.join('\n'));
    if (tokens + sectionTokens > budget) break;
    lines.push(...sectionLines);
    tokens += sectionTokens;
  }

  return lines.join('\n');
}

function exportGemini(shellPath) {
  return render(loadShell(shellPath), TOKEN_BUDGET);
}

module.exports = { exportGemini };
