'use strict';

const { loadShell, estimateTokens } = require('./base');

const TOKEN_BUDGET = 100_000;

function render({ meta, shellLayer, sections }, budget) {
  const lines = [];
  const date = new Date().toISOString().slice(0, 10);

  lines.push(`<!-- Generated by cas export generic — ${date} -->`);
  lines.push(`<!-- Shell: ${meta.owner} | Type: ${meta.type} | CAS: ${meta.cas_version} -->`);
  lines.push('');
  lines.push(`# Context: ${meta.owner}`);
  lines.push('');
  lines.push(`**Type:** ${meta.type} | **Domain:** ${meta.domain} | **CAS version:** ${meta.cas_version}`);
  lines.push('');

  if (shellLayer.length > 0) {
    lines.push('---');
    lines.push('');
    lines.push('## Shell Framework');
    lines.push('');
    for (const { name, content } of shellLayer) {
      lines.push(`### ${name}`);
      lines.push('');
      lines.push(content.trim());
      lines.push('');
    }
  }

  let tokens = estimateTokens(lines.join('\n'));

  for (const { label, files } of sections) {
    const sectionLines = ['---', '', `## ${label}`, ''];
    for (const { name, content } of files) {
      sectionLines.push(`### ${name}`);
      sectionLines.push('');
      sectionLines.push(content.trim());
      sectionLines.push('');
    }
    const sectionTokens = estimateTokens(sectionLines.join('\n'));
    if (tokens + sectionTokens > budget) break;
    lines.push(...sectionLines);
    tokens += sectionTokens;
  }

  return lines.join('\n');
}

function exportGeneric(shellPath) {
  return render(loadShell(shellPath), TOKEN_BUDGET);
}

module.exports = { exportGeneric };
