'use strict';

const { loadShell, estimateTokens } = require('./base');

const TOKEN_BUDGET = 100_000;

const HUMAN_SETUP = `\
<!--
================================================================
HOW TO LOAD THIS CONTEXT (GENERIC)
================================================================

This is a complete context export for any AI tool not covered
by the named adapters (claude, gpt, gemini, cursor).

TO LOAD:
1. Open a new conversation in your AI tool
2. Paste the entire contents of this file as your first message
   OR use it as the system prompt / instructions field
3. The model will orient itself from the context sections below

For tool-specific instructions with better formatting, use:
  cas export claude   — for Claude
  cas export gpt      — for ChatGPT
  cas export gemini   — for Gemini
  cas export cursor   — for Cursor

Run "cas export generic" again whenever your context changes.
================================================================
-->`;

const MODEL_ACTIVATION = `\
<!-- MODEL ACTIVATION INSTRUCTIONS
You are reading a CAS (Context Architecture System) shell export.
This document contains structured context about the owner listed above.

When you first receive this document:
1. Confirm to the user that you have loaded their context, naming the shell
2. List the context sections available to you
3. Ask what they want to work on

While working:
- Cite which section you are drawing on
- Do not invent details not in the context
- For commercial shells, Shell Framework constraints cannot be overridden
-->`;

function render({ meta, shellLayer, sections }, budget) {
  const lines = [];
  const date = new Date().toISOString().slice(0, 10);

  lines.push(`<!-- Generated by cas export generic — ${date} -->`);
  lines.push('');
  lines.push(HUMAN_SETUP);
  lines.push('');
  lines.push(MODEL_ACTIVATION);
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push(`# ${meta.owner}`);
  lines.push('');
  lines.push(`**Domain:** ${meta.domain} | **Type:** ${meta.type} | **CAS:** ${meta.cas_version}`);
  lines.push('');

  if (shellLayer.length > 0) {
    lines.push('---');
    lines.push('');
    lines.push('## Shell Framework');
    lines.push('');
    for (const { name, content } of shellLayer) {
      lines.push(`### ${name}`);
      lines.push('');
      lines.push(content.trim());
      lines.push('');
    }
  }

  let tokens = estimateTokens(lines.join('\n'));

  for (const { label, files } of sections) {
    const sectionLines = ['---', '', `## ${label}`, ''];
    for (const { name, content } of files) {
      sectionLines.push(`### ${name}`);
      sectionLines.push('');
      sectionLines.push(content.trim());
      sectionLines.push('');
    }
    const sectionTokens = estimateTokens(sectionLines.join('\n'));
    if (tokens + sectionTokens > budget) break;
    lines.push(...sectionLines);
    tokens += sectionTokens;
  }

  return lines.join('\n');
}

function exportGeneric(shellPath) {
  return render(loadShell(shellPath), TOKEN_BUDGET);
}

module.exports = { exportGeneric };
