'use strict';

const { loadShell, estimateTokens } = require('./base');

const TOKEN_BUDGET = 50_000;

const PREAMBLE = `You have been loaded with structured business context via the Context Architecture System (CAS). \
Use the sections below to inform all responses. Cite the relevant section when drawing on it. \
Do not fabricate details not present in this context.`;

function render({ meta, shellLayer, sections }, budget) {
  const lines = [];
  const date = new Date().toISOString().slice(0, 10);

  lines.push(`<!-- Generated by cas export gpt — ${date} -->`);
  lines.push('');
  lines.push(`# ${meta.owner}`);
  lines.push('');
  lines.push(`**Domain:** ${meta.domain}`);
  lines.push('');
  lines.push(PREAMBLE);
  lines.push('');

  if (shellLayer.length > 0) {
    lines.push('---');
    lines.push('');
    lines.push('## Shell Framework');
    lines.push('');
    for (const { name, content } of shellLayer) {
      lines.push(`### ${name}`);
      lines.push('');
      lines.push(content.trim());
      lines.push('');
    }
  }

  let tokens = estimateTokens(lines.join('\n'));

  for (const { label, files } of sections) {
    const sectionLines = ['---', '', `## ${label}`, ''];
    for (const { name, content } of files) {
      sectionLines.push(`### ${name}`);
      sectionLines.push('');
      sectionLines.push(content.trim());
      sectionLines.push('');
    }
    const sectionTokens = estimateTokens(sectionLines.join('\n'));
    if (tokens + sectionTokens > budget) break;
    lines.push(...sectionLines);
    tokens += sectionTokens;
  }

  return lines.join('\n');
}

function exportGpt(shellPath) {
  return render(loadShell(shellPath), TOKEN_BUDGET);
}

module.exports = { exportGpt };
