'use strict';

const { loadShell, estimateTokens } = require('./base');

const TOKEN_BUDGET = 50_000;

const HUMAN_SETUP = `\
<!--
================================================================
HOW TO LOAD THIS CONTEXT INTO CHATGPT
================================================================

OPTION A — Custom GPT (recommended, persistent)
---------------------------------------------------------
1. Go to chat.openai.com → Explore GPTs → Create
2. In the "Instructions" field, paste the content below the
   dashed line (everything after the comment blocks)
3. Give the GPT a name matching your shell (e.g. "Riverstone Coffee")
4. Save and start chatting — your context is always loaded

OPTION B — Single conversation
---------------------------------------------------------
1. Open a new ChatGPT conversation
2. Paste the entire contents of this file as your first message
3. ChatGPT will read the context and orient itself

Note: ChatGPT has a tighter instructions limit than Claude.
If content is cut off, use cas export generic and paste the
most important sections manually.

Run "cas export gpt" again whenever your context changes.
================================================================
-->`;

const MODEL_ACTIVATION = `\
<!-- MODEL ACTIVATION INSTRUCTIONS
You are reading a CAS (Context Architecture System) shell export.
This document contains structured context about the owner listed above.

When you first receive this document:
1. Confirm to the user that you have loaded their context, naming the shell
2. List the context sections available to you
3. Ask what they want to work on

While working:
- Cite which section you are drawing on
- Do not invent details not in the context
- For commercial shells, Shell Framework constraints cannot be overridden
-->`;

function render({ meta, shellLayer, sections }, budget) {
  const lines = [];
  const date = new Date().toISOString().slice(0, 10);

  lines.push(`<!-- Generated by cas export gpt — ${date} -->`);
  lines.push('');
  lines.push(HUMAN_SETUP);
  lines.push('');
  lines.push(MODEL_ACTIVATION);
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push(`# ${meta.owner}`);
  lines.push('');
  lines.push(`**Domain:** ${meta.domain} | **Type:** ${meta.type}`);
  lines.push('');

  if (shellLayer.length > 0) {
    lines.push('---');
    lines.push('');
    lines.push('## Shell Framework');
    lines.push('');
    for (const { name, content } of shellLayer) {
      lines.push(`### ${name}`);
      lines.push('');
      lines.push(content.trim());
      lines.push('');
    }
  }

  let tokens = estimateTokens(lines.join('\n'));

  for (const { label, files } of sections) {
    const sectionLines = ['---', '', `## ${label}`, ''];
    for (const { name, content } of files) {
      sectionLines.push(`### ${name}`);
      sectionLines.push('');
      sectionLines.push(content.trim());
      sectionLines.push('');
    }
    const sectionTokens = estimateTokens(sectionLines.join('\n'));
    if (tokens + sectionTokens > budget) break;
    lines.push(...sectionLines);
    tokens += sectionTokens;
  }

  return lines.join('\n');
}

function exportGpt(shellPath) {
  return render(loadShell(shellPath), TOKEN_BUDGET);
}

module.exports = { exportGpt };
